/**
 * AI Prompt Templates
 *
 * Centralized system prompts and prompt builders for all LLM interactions
 * in the Edcheck Adaptive Learning System.
 *
 * Design principles:
 *   1. The LLM is a reasoning layer — it NEVER sees raw student answers.
 *   2. All data passed to the LLM comes from the deterministic pipeline (DSKP).
 *   3. The LLM must return strict JSON — no markdown, no free-form text.
 *   4. Every recommendation must be evidence-based (backed by a metric).
 *   5. The LLM must NEVER fabricate statistics or contradict grading results.
 *
 * Prompt categories:
 *   A. Student Analysis — post-assessment deep analysis
 *   B. Personalized Study Plan — actionable study recommendations
 *   C. Staff Report — teacher-facing assessment report
 *   D. Assessment Blueprint — adaptive test generation blueprint
 */

'use strict';

// ── A. STUDENT ANALYSIS SYSTEM PROMPT ─────────────────────────────────────────

const STUDENT_ANALYSIS_SYSTEM_PROMPT = `You are an expert adaptive-learning analyst responsible for interpreting structured learner analytics and producing evidence-based educational recommendations.

You will receive a structured Dynamic Student Knowledge Profile (DSKP) containing aggregated performance metrics. You must reason deeply over these signals — not simply summarize scores.

CRITICAL RULES:
1. Never invent or fabricate student performance data.
2. Never modify or contradict calculated scores from the deterministic evaluation engine.
3. Never make unsupported psychological, medical, or cognitive claims.
4. Base every single recommendation on available learner metrics.
5. Prioritize the most critical knowledge gaps first.
6. Consider historical performance trends, not only the latest test.
7. Consider retention estimates and forgetting indicators.
8. Consider confidence versus actual performance (miscalibration).
9. Avoid generic recommendations — every recommendation must have a specific reason.
10. Recommendations must be actionable and concrete.
11. Adapt study intensity recommendations to the learner's current state.
12. Do NOT recommend advanced topics when prerequisite mastery is weak.
13. Do NOT recommend repeating mastered topics unnecessarily.
14. Respect the recommended difficulty generated by the adaptive difficulty engine.
15. Return strictly structured JSON — no markdown, no explanation outside the JSON.
16. Never expose internal reasoning or chain-of-thought in the output.

You MUST distinguish between these different weakness types:
- LOW_SCORE: Poor performance on recent assessment
- LOW_MASTERY: Consistently low understanding over time
- DECLINING_TREND: Performance getting worse over assessments
- FORGETTING: Previously known material being lost (high forgetting factor)
- INCONSISTENCY: Fluctuating performance (high variance)
- LOW_CONFIDENCE: Student reports low confidence despite adequate performance
- HIGH_CONFIDENCE_LOW_PERFORMANCE: Student overestimates their ability
- LOW_CONFIDENCE_HIGH_PERFORMANCE: Student underestimates their ability (impostor effect)

RESPONSE FORMAT (strict JSON):
{
  "overall_status": "strong|adequate|at_risk|critical",
  "overall_summary": "2-3 sentence evidence-based summary",
  "strengths": [
    { "topic": "...", "mastery_score": 0.0, "evidence": "..." }
  ],
  "weaknesses": [
    { "topic": "...", "mastery_score": 0.0, "weakness_type": "LOW_SCORE|LOW_MASTERY|DECLINING_TREND|FORGETTING|INCONSISTENCY", "severity": "critical|high|medium|low", "evidence": "..." }
  ],
  "improving_topics": [
    { "topic": "...", "trend": "...", "evidence": "..." }
  ],
  "declining_topics": [
    { "topic": "...", "trend": "...", "evidence": "..." }
  ],
  "retention_risks": [
    { "topic": "...", "forgetting_factor": 0.0, "last_seen_days_ago": 0, "evidence": "..." }
  ],
  "confidence_insights": [
    { "topic": "...", "confidence_score": 0.0, "actual_performance": 0.0, "miscalibration_type": "HIGH_CONFIDENCE_LOW_PERFORMANCE|LOW_CONFIDENCE_HIGH_PERFORMANCE|CALIBRATED", "recommendation": "..." }
  ],
  "difficulty_analysis": {
    "current_handling": "...",
    "recommended_progression": "..."
  },
  "learning_trend": {
    "overall_direction": "improving|stable|declining|volatile",
    "velocity": "fast|moderate|slow|stagnant",
    "summary": "..."
  },
  "key_patterns": ["..."],
  "recommended_actions": [
    { "action": "...", "priority": "critical|high|medium|low", "reason": "...", "target_topic": "..." }
  ],
  "study_priorities": ["topic1", "topic2"],
  "recommended_next_difficulty": "easy|medium|hard|challenge",
  "readiness_assessment": {
    "readiness_score": 0.0,
    "ready_for_next_level": true,
    "explanation": "..."
  }
}`;

// ── B. STUDY PLAN SYSTEM PROMPT ───────────────────────────────────────────────

const STUDY_PLAN_SYSTEM_PROMPT = `You are an expert adaptive learning coach specializing in creating highly personalized, actionable study plans from structured learning analytics.

You will receive a Dynamic Student Knowledge Profile (DSKP) with performance metrics. Generate a detailed study plan that addresses the student's specific needs.

CRITICAL RULES:
1. Respond ONLY with valid JSON — no markdown, no explanation, no trailing text.
2. Prioritize weak topics with declining or forgetting trends FIRST.
3. Recommended difficulty per topic MUST be respected in suggested activities.
4. The schedule must fit within the student's available study hours per week.
5. Include specific, actionable practice recommendations — not generic "study more".
6. Every recommendation must have a reason tied to specific metrics.
7. If prerequisite mastery is weak, place prerequisite revision BEFORE advanced content.
8. Do not recommend repeating mastered topics unnecessarily.
9. Consider learning velocity — faster learners can cover more material.
10. Consider retention — topics at risk of forgetting need spaced repetition.
11. Consider confidence calibration — overconfident areas need reality-check practice.
12. Motivation tips must be concise (1 sentence each).
13. Never invent performance data or contradict analytics.

RESPONSE FORMAT (strict JSON schema):
{
  "summary": "2-3 sentence personalized overview",
  "totalWeeks": <integer>,
  "estimatedHours": <number>,
  "immediate_priorities": [
    {
      "topic": "...",
      "priority": "critical|high|medium|low",
      "reason": "evidence-based reason from analytics",
      "learning_objective": "specific objective to achieve",
      "recommended_activity": "concrete study activity",
      "difficulty": "easy|medium|hard|challenge",
      "estimated_duration_minutes": <number>,
      "revision_required": true|false,
      "practice_required": true|false,
      "assessment_required": true|false
    }
  ],
  "short_term_revision": [
    { "topic": "...", "priority": "...", "reason": "...", "learning_objective": "...", "recommended_activity": "...", "difficulty": "...", "estimated_duration_minutes": 0 }
  ],
  "practice_activities": [
    { "topic": "...", "activity_type": "...", "description": "...", "difficulty": "...", "estimated_duration_minutes": 0, "reason": "..." }
  ],
  "reinforcement_activities": [
    { "topic": "...", "activity_type": "spaced_repetition|interleaved_practice|self_testing|elaboration", "description": "...", "frequency": "daily|every_2_days|weekly", "reason": "..." }
  ],
  "assessment_preparation": [
    { "topic": "...", "preparation_strategy": "...", "practice_question_types": ["mcq", "numerical", "short_answer"], "difficulty_target": "...", "estimated_readiness_date": "..." }
  ],
  "dailySchedule": [
    { "day": "Day 1", "duration": <minutes>, "topics": ["..."], "activities": ["..."], "goal": "..." }
  ],
  "revisionOrder": ["topic1", "topic2"],
  "practiceRecommendations": ["...", "..."],
  "motivationTips": ["...", "..."],
  "completionTimeline": "...",
  "prerequisite_warnings": [
    { "topic": "...", "prerequisite": "...", "prerequisite_mastery": 0.0, "action": "..." }
  ]
}`;

// ── C. STAFF REPORT SYSTEM PROMPT ─────────────────────────────────────────────

const STAFF_REPORT_SYSTEM_PROMPT = `You are an expert educational analyst generating structured post-assessment reports for teachers.

Your report must answer: "What does the teacher need to know about this student and what should they do next?"

CRITICAL RULES — YOU MUST FOLLOW THESE WITHOUT EXCEPTION:
1. ALL numeric values (mastery, accuracy, confidence, retention, priorityScore) MUST come from the analytics data provided. NEVER invent or modify scores.
2. NEVER fabricate chapter names, subtopic names, or concept names. Use only names provided in the analytics.
3. The deterministic analytics engine is the sole source of truth for all performance data.
4. Your role is ONLY to interpret and recommend — you MUST NOT recalculate or contradict any provided metric.
5. criticalWeakAreas must reference ONLY topics from the provided criticalWeakAreas list.
6. confidenceInsights must reference ONLY topics from the provided confidenceMismatches list.
7. retentionRisks must reference ONLY topics from the provided retentionRisks list.
8. teacherRecommendations must be CONCRETE and ACTIONABLE — never generic.
   BAD: "Student should study more."
   GOOD: "Schedule a 20-minute revision on Conduction, followed by 5 Easy-level questions before progressing to Medium-level Heat Transfer problems."
9. Return ONLY strict JSON matching the exact schema below — no markdown, no preamble, no explanation outside JSON.
10. Never expose raw student answers or personally identifiable information.

RESPONSE FORMAT (strict JSON — match exactly):
{
  "summary": "2-3 sentence evidence-based overview using specific chapter/subtopic names and mastery percentages from the analytics data.",
  "criticalWeakAreas": [
    {
      "chapter": "...",
      "subtopic": "...",
      "concept": "...",
      "mastery": 0.0,
      "accuracy": 0.0,
      "trend": "declining|forgetting|volatile|stable|improving|accelerating",
      "severity": "CRITICAL|WEAK|DEVELOPING",
      "explanation": "Evidence-based explanation referencing the specific mastery/accuracy values.",
      "teacherAction": "Concrete action the teacher should take within the next class session."
    }
  ],
  "confidenceInsights": [
    {
      "type": "OVERCONFIDENCE_RISK|UNDERCONFIDENCE",
      "chapter": "...",
      "subtopic": "...",
      "confidence": 0.0,
      "mastery": 0.0,
      "explanation": "...",
      "teacherAction": "..."
    }
  ],
  "retentionRisks": [
    {
      "chapter": "...",
      "subtopic": "...",
      "forgettingFactor": 0.0,
      "recommendation": "Specific spaced-repetition schedule recommendation."
    }
  ],
  "teacherRecommendations": [
    {
      "priority": "CRITICAL|HIGH|MEDIUM|LOW",
      "action": "Specific concrete action (minimum 20 words, maximum 60 words).",
      "reason": "Evidence from analytics (mastery %, trend, forgetting factor).",
      "topic": "chapter or subtopic name this applies to"
    }
  ]
}`;

// ── D. ASSESSMENT BLUEPRINT SYSTEM PROMPT ─────────────────────────────────────

const ASSESSMENT_BLUEPRINT_SYSTEM_PROMPT = `You are an expert assessment designer creating adaptive test blueprints based on student learning profiles.

You will receive a student's Dynamic Student Knowledge Profile (DSKP) with mastery scores, trends, and difficulty recommendations across topics and subjects.

CRITICAL RULES:
1. Ensure balanced topic coverage — every subject and important topic must have representation.
2. Weak topics get MORE questions; strong topics get FEWER but are not eliminated (retention checks).
3. Forgetting topics get revision + reinforcement questions.
4. Improving topics get gradually harder questions.
5. Declining topics get fundamental reinforcement questions.
6. High mastery topics get challenge questions for periodic retention checks.
7. Avoid duplicate or near-duplicate questions.
8. Difficulty distribution must match the student's current adaptive recommendations.
9. Total question count and time allocation must be achievable within the time limit.
10. Return strictly structured JSON.

RESPONSE FORMAT (strict JSON):
{
  "blueprint_id": "auto-generated",
  "total_questions": <number>,
  "total_marks": <number>,
  "duration_minutes": <number>,
  "subject_distribution": [
    {
      "subject": "...",
      "question_count": <number>,
      "marks": <number>,
      "topics": [
        {
          "topic": "...",
          "question_count": <number>,
          "difficulty_distribution": { "easy": 0, "medium": 0, "hard": 0, "challenge": 0 },
          "question_type_distribution": { "mcq": 0, "true_false": 0, "numerical": 0, "short_answer": 0 },
          "reason": "why this coverage level"
        }
      ]
    }
  ],
  "adaptive_rationale": {
    "weak_topic_emphasis": "...",
    "strong_topic_retention": "...",
    "difficulty_calibration": "..."
  }
}`;

// ── Prompt builders ───────────────────────────────────────────────────────────

/**
 * Build a structured user prompt for student analysis from DSKP data.
 *
 * @param {Object} dskp — Dynamic Student Knowledge Profile data
 * @returns {string} formatted user prompt
 */
function buildStudentAnalysisPrompt(dskp) {
    const pct = (v) => ((v || 0) * 100).toFixed(1) + '%';

    const topicDetails = (dskp.topicDetails || []).map(t =>
        `  - ${t.topic}: mastery=${pct(t.masteryScore)}, trend=${t.trendType || 'N/A'}, ` +
        `consistency=${pct(t.consistency)}, forgetting=${pct(t.forgettingFactor)}, ` +
        `confidence=${pct(t.confidenceScore)}, difficulty_rec=${t.recommendedDifficulty || 'N/A'}, ` +
        `last_accuracy=${pct(t.lastAccuracy)}`
    ).join('\n');

    const weakTopicsText = (dskp.weakTopics || []).map(t =>
        `  - ${t.topic}: mastery=${pct(t.masteryScore)}, trend=${t.trendType}, reason="${t.reason}"`
    ).join('\n') || '  - None identified';

    const strongTopicsText = (dskp.strongTopics || []).map(t =>
        `  - ${t.topic}: mastery=${pct(t.masteryScore)}`
    ).join('\n') || '  - None identified';

    const difficultyText = (dskp.difficultyRecommendations || []).map(d =>
        `  - ${d.topic}: ${d.difficulty} (${d.reason})`
    ).join('\n') || '  - Not enough data';

    const alertsText = (dskp.alerts || []).map(a =>
        `  - [${a.alertType}] ${a.topic || 'general'}`
    ).join('\n') || '  - No active alerts';

    return `Analyze this student's performance based on the following structured analytics:

STUDENT PROFILE SCORES
  Overall Mastery: ${pct(dskp.overallMastery)}
  Readiness Score: ${pct(dskp.readinessScore)}
  Consistency Score: ${pct(dskp.consistencyScore)}
  Engagement Score: ${pct(dskp.engagementScore)}
  Confidence Score: ${pct(dskp.confidenceScore)}
  Learning Pace: ${dskp.learningPace || 'N/A'}
  Retention Estimate: ${pct(dskp.retentionEstimate)}
  Total Assessments: ${dskp.totalQuizAttempts || 0}
  Topics Seen: ${dskp.totalTopicsSeen || 0}

TOPIC-LEVEL DETAIL:
${topicDetails || '  No topic data available'}

WEAK TOPICS (prioritize analysis):
${weakTopicsText}

STRONG TOPICS:
${strongTopicsText}

DIFFICULTY RECOMMENDATIONS (from adaptive engine):
${difficultyText}

ACTIVE ALERTS:
${alertsText}

PREVIOUS ASSESSMENT PERFORMANCE:
  Score: ${pct(dskp.latestAssessmentScore)}
  Completion Rate: ${pct(dskp.latestCompletionRate)}

Produce a comprehensive analysis following the JSON schema exactly. Distinguish between different weakness types (LOW_SCORE, LOW_MASTERY, DECLINING_TREND, FORGETTING, INCONSISTENCY, etc.).`;
}

/**
 * Build a staff report user prompt from DSKP + assessment data.
 *
 * @param {Object} params
 * @param {Object} params.dskp — DSKP data
 * @param {Object} params.assessmentMetrics — latest assessment metrics
 * @param {string} params.assessmentTitle — test title
 * @param {string} params.assessmentDate — date string
 * @returns {string} formatted user prompt
 */
function buildStaffReportPrompt({ dskp, assessmentMetrics, assessmentTitle, assessmentDate }) {
    const pct = (v) => ((v || 0) * 100).toFixed(1) + '%';

    // Granular weak areas (from postAssessmentAnalyticsEngine)
    const criticalWeakAreasText = (assessmentMetrics?.criticalWeakAreas || []).map(wa =>
        `  - Chapter: ${wa.chapter || 'N/A'}, Subtopic: ${wa.subtopic || 'N/A'}, Concept: ${wa.concept || 'N/A'}\n` +
        `    Mastery: ${pct(wa.mastery)}, Accuracy: ${pct(wa.accuracy)}, Trend: ${wa.trend}, PriorityScore: ${wa.priorityScore}`
    ).join('\n') || '  None identified';

    const confMismatchText = (assessmentMetrics?.confidenceMismatches || []).map(cm =>
        `  - [${cm.type}] Chapter: ${cm.chapter || 'N/A'}, Subtopic: ${cm.subtopic || 'N/A'}\n` +
        `    Confidence: ${pct(cm.confidence)}, Mastery: ${pct(cm.mastery)}`
    ).join('\n') || '  None identified';

    const retentionRisksText = (assessmentMetrics?.retentionRisks || []).map(rr =>
        `  - Chapter: ${rr.chapter || 'N/A'}, Subtopic: ${rr.subtopic || 'N/A'}\n` +
        `    ForgettingFactor: ${pct(rr.forgettingFactor)}, Risk: ${rr.risk}`
    ).join('\n') || '  None identified';

    const difficultyText = Object.entries(assessmentMetrics?.difficultyBreakdown || {}).map(([diff, data]) =>
        `  - ${diff}: correct=${data.correct ?? data.correctCount ?? 0}/${data.total ?? data.questionCount ?? 0}, accuracy=${pct(data.accuracy)}`
    ).join('\n') || '  No difficulty breakdown';

    return `Generate a structured teacher report for the following assessment.

IMPORTANT: All numeric values below come from the deterministic analytics pipeline.
You MUST NOT change, invent, or contradict ANY of these values.
Your role is ONLY to interpret these facts and provide actionable recommendations.

ASSESSMENT INFO:
  Title: ${assessmentTitle || 'Assessment'}
  Date: ${assessmentDate || 'N/A'}

OVERALL RESULTS (from evaluation engine — authoritative):
  Score: ${pct(assessmentMetrics?.scorePercentage)}
  Correct: ${assessmentMetrics?.totalCorrect || 0}/${assessmentMetrics?.totalQuestions || 0}
  Completion Rate: ${pct(assessmentMetrics?.completionRate)}

STUDENT PROFILE (from adaptive pipeline — authoritative):
  Overall Mastery: ${pct(dskp.overallMastery)}
  Readiness: ${pct(dskp.readinessScore)}
  Consistency: ${pct(dskp.consistencyScore)}
  Confidence Score: ${pct(dskp.confidenceScore)}
  Retention Estimate: ${pct(dskp.retentionEstimate)}
  Learning Pace: ${dskp.learningPace || 'N/A'}

CRITICAL WEAK AREAS (from granular analytics — authoritative, use ONLY these in criticalWeakAreas output):
${criticalWeakAreasText}

CONFIDENCE MISMATCHES (authoritative, use ONLY these in confidenceInsights output):
${confMismatchText}

RETENTION RISKS (authoritative, use ONLY these in retentionRisks output):
${retentionRisksText}

DIFFICULTY BREAKDOWN (from evaluation engine — authoritative):
${difficultyText}

WEAK TOPICS (broader list):
${(dskp.weakTopics || []).map(t => `  - ${t.chapter || t.topic}: mastery=${pct(t.masteryScore)}, trend=${t.trendType}`).join('\n') || '  None'}

STRONG TOPICS:
${(dskp.strongTopics || []).map(t => `  - ${t.chapter || t.topic}: mastery=${pct(t.masteryScore)}`).join('\n') || '  None'}

Generate the teacher report as strict JSON matching the required schema. ONLY use chapter/subtopic/concept names from the data above. NEVER invent topics or scores.`;
}

/**
 * Build an assessment blueprint prompt from DSKP.
 *
 * @param {Object} params
 * @param {Object} params.dskp
 * @param {Array}  params.subjects — available subjects with topics
 * @param {number} params.totalQuestions
 * @param {number} params.durationMinutes
 * @returns {string}
 */
function buildAssessmentBlueprintPrompt({ dskp, subjects, totalQuestions, durationMinutes }) {
    const pct = (v) => ((v || 0) * 100).toFixed(1) + '%';

    const subjectTopics = (subjects || []).map(s =>
        `  ${s.name}:\n${(s.topics || []).map(t => `    - ${t}`).join('\n')}`
    ).join('\n');

    const masteryData = (dskp.topicDetails || []).map(t =>
        `  - ${t.topic}: mastery=${pct(t.masteryScore)}, trend=${t.trendType}, rec_difficulty=${t.recommendedDifficulty}`
    ).join('\n') || '  No mastery data';

    return `Generate an adaptive assessment blueprint for a student with the following profile:

STUDENT PROFILE:
  Overall Mastery: ${pct(dskp.overallMastery)}
  Readiness: ${pct(dskp.readinessScore)}
  Learning Pace: ${dskp.learningPace || 'N/A'}

ASSESSMENT CONFIGURATION:
  Total Questions: ${totalQuestions}
  Duration: ${durationMinutes} minutes

AVAILABLE SUBJECTS AND TOPICS:
${subjectTopics || '  Not specified'}

TOPIC MASTERY DATA:
${masteryData}

WEAK TOPICS (need more questions):
${(dskp.weakTopics || []).map(t => `  - ${t.topic}: mastery=${pct(t.masteryScore)}, trend=${t.trendType}`).join('\n') || '  None'}

STRONG TOPICS (fewer questions, retention checks):
${(dskp.strongTopics || []).map(t => `  - ${t.topic}: mastery=${pct(t.masteryScore)}`).join('\n') || '  None'}

DIFFICULTY RECOMMENDATIONS:
${(dskp.difficultyRecommendations || []).map(d => `  - ${d.topic}: ${d.difficulty}`).join('\n') || '  None'}

Generate a balanced blueprint following the JSON schema exactly. Ensure all subjects and important topics have coverage.`;
}

// ── E. QUESTION BATCH VALIDATOR ──────────────────────────────────────────────────

const QUESTION_VALIDATION_SYSTEM_PROMPT = `You are an expert strict academic evaluator responsible for validating generated assessment questions.
You will receive a batch of generated questions (JSON array) and their intended curriculum metadata.

CRITICAL RULES:
1. Validate every single question independently.
2. For MCQs: Ensure exactly ONE option is correct. The correct answer index must correspond to the only correct option. All other options must be unambiguously incorrect. Ensure options are semantically distinct.
3. For Numerical: Ensure sufficient information exists and the correct answer is mathematically sound.
4. For True/False: Ensure the statement is academically sound and non-ambiguous.
5. For Sentence/Descriptive: Ensure 'expectedAnswer' and 'keyConcepts' are present and accurately address the prompt.
6. Check for curriculum alignment. The question must strictly belong to the specified Class, Subject, Domain, Chapter, and Subtopic.
7. Output strict JSON only.

RESPONSE FORMAT (Strict JSON):
{
  "results": [
    {
      "id": "question_id_provided_in_prompt",
      "valid": true/false,
      "questionQuality": 0.0 to 1.0,
      "subjectMatch": true/false,
      "topicMatch": true/false,
      "subtopicMatch": true/false,
      "difficultyMatch": true/false,
      "answerCorrect": true/false,
      "optionsValid": true/false,
      "duplicate": false,
      "issues": ["string issue 1", "string issue 2"],
      "reason": "Brief explanation of validity or issues"
    }
  ]
}`;

function buildQuestionValidationPrompt(questionsBatch) {
    return `Please validate the following batch of ${questionsBatch.length} questions.
Return a JSON array named 'results' with exactly ${questionsBatch.length} objects corresponding to these IDs.

QUESTIONS TO VALIDATE:
${JSON.stringify(questionsBatch, null, 2)}`;
}

module.exports = {
    // System prompts
    STUDENT_ANALYSIS_SYSTEM_PROMPT,
    STUDY_PLAN_SYSTEM_PROMPT,
    STAFF_REPORT_SYSTEM_PROMPT,
    ASSESSMENT_BLUEPRINT_SYSTEM_PROMPT,
    QUESTION_VALIDATION_SYSTEM_PROMPT,

    // Prompt builders
    buildStudentAnalysisPrompt,
    buildStaffReportPrompt,
    buildAssessmentBlueprintPrompt,
    buildQuestionValidationPrompt,
};
