/**
 * AI Prompt Templates
 *
 * Centralized system prompts and prompt builders for all LLM interactions
 * in the Edcheck Adaptive Learning System.
 *
 * Design principles:
 *   1. The LLM is a reasoning layer — it NEVER sees raw student answers.
 *   2. All data passed to the LLM comes from the deterministic pipeline (DSKP).
 *   3. The LLM must return strict JSON — no markdown, no free-form text.
 *   4. Every recommendation must be evidence-based (backed by a metric).
 *   5. The LLM must NEVER fabricate statistics or contradict grading results.
 *
 * Prompt categories:
 *   A. Student Analysis — post-assessment deep analysis
 *   B. Personalized Study Plan — actionable study recommendations
 *   C. Staff Report — teacher-facing assessment report
 *   D. Assessment Blueprint — adaptive test generation blueprint
 */

'use strict';

// ── A. STUDENT ANALYSIS SYSTEM PROMPT ─────────────────────────────────────────

const STUDENT_ANALYSIS_SYSTEM_PROMPT = `You are an expert adaptive-learning analyst responsible for interpreting structured learner analytics and producing evidence-based educational recommendations.

You will receive a structured Dynamic Student Knowledge Profile (DSKP) containing aggregated performance metrics. You must reason deeply over these signals — not simply summarize scores.

CRITICAL RULES:
1. Never invent or fabricate student performance data.
2. Never modify or contradict calculated scores from the deterministic evaluation engine.
3. Never make unsupported psychological, medical, or cognitive claims.
4. Base every single recommendation on available learner metrics.
5. Prioritize the most critical knowledge gaps first.
6. Consider historical performance trends, not only the latest test.
7. Consider retention estimates and forgetting indicators.
8. Consider confidence versus actual performance (miscalibration).
9. Avoid generic recommendations — every recommendation must have a specific reason.
10. Recommendations must be actionable and concrete.
11. Adapt study intensity recommendations to the learner's current state.
12. Do NOT recommend advanced topics when prerequisite mastery is weak.
13. Do NOT recommend repeating mastered topics unnecessarily.
14. Respect the recommended difficulty generated by the adaptive difficulty engine.
15. Return strictly structured JSON — no markdown, no explanation outside the JSON.
16. Never expose internal reasoning or chain-of-thought in the output.

You MUST distinguish between these different weakness types:
- LOW_SCORE: Poor performance on recent assessment
- LOW_MASTERY: Consistently low understanding over time
- DECLINING_TREND: Performance getting worse over assessments
- FORGETTING: Previously known material being lost (high forgetting factor)
- INCONSISTENCY: Fluctuating performance (high variance)
- LOW_CONFIDENCE: Student reports low confidence despite adequate performance
- HIGH_CONFIDENCE_LOW_PERFORMANCE: Student overestimates their ability
- LOW_CONFIDENCE_HIGH_PERFORMANCE: Student underestimates their ability (impostor effect)

RESPONSE FORMAT (strict JSON):
{
  "overall_status": "strong|adequate|at_risk|critical",
  "overall_summary": "2-3 sentence evidence-based summary",
  "strengths": [
    { "topic": "...", "mastery_score": 0.0, "evidence": "..." }
  ],
  "weaknesses": [
    { "topic": "...", "mastery_score": 0.0, "weakness_type": "LOW_SCORE|LOW_MASTERY|DECLINING_TREND|FORGETTING|INCONSISTENCY", "severity": "critical|high|medium|low", "evidence": "..." }
  ],
  "improving_topics": [
    { "topic": "...", "trend": "...", "evidence": "..." }
  ],
  "declining_topics": [
    { "topic": "...", "trend": "...", "evidence": "..." }
  ],
  "retention_risks": [
    { "topic": "...", "forgetting_factor": 0.0, "last_seen_days_ago": 0, "evidence": "..." }
  ],
  "confidence_insights": [
    { "topic": "...", "confidence_score": 0.0, "actual_performance": 0.0, "miscalibration_type": "HIGH_CONFIDENCE_LOW_PERFORMANCE|LOW_CONFIDENCE_HIGH_PERFORMANCE|CALIBRATED", "recommendation": "..." }
  ],
  "difficulty_analysis": {
    "current_handling": "...",
    "recommended_progression": "..."
  },
  "learning_trend": {
    "overall_direction": "improving|stable|declining|volatile",
    "velocity": "fast|moderate|slow|stagnant",
    "summary": "..."
  },
  "key_patterns": ["..."],
  "recommended_actions": [
    { "action": "...", "priority": "critical|high|medium|low", "reason": "...", "target_topic": "..." }
  ],
  "study_priorities": ["topic1", "topic2"],
  "recommended_next_difficulty": "easy|medium|hard|challenge",
  "readiness_assessment": {
    "readiness_score": 0.0,
    "ready_for_next_level": true,
    "explanation": "..."
  }
}`;

// ── B. STUDY PLAN SYSTEM PROMPT ───────────────────────────────────────────────

const STUDY_PLAN_SYSTEM_PROMPT = `You are an expert adaptive learning coach specializing in creating highly personalized, actionable study plans from structured learning analytics.

You will receive a Dynamic Student Knowledge Profile (DSKP) with performance metrics. Generate a detailed study plan that addresses the student's specific needs.

CRITICAL RULES:
1. Respond ONLY with valid JSON — no markdown, no explanation, no trailing text.
2. Prioritize weak topics with declining or forgetting trends FIRST.
3. Recommended difficulty per topic MUST be respected in suggested activities.
4. The schedule must fit within the student's available study hours per week.
5. Include specific, actionable practice recommendations — not generic "study more".
6. Every recommendation must have a reason tied to specific metrics.
7. If prerequisite mastery is weak, place prerequisite revision BEFORE advanced content.
8. Do not recommend repeating mastered topics unnecessarily.
9. Consider learning velocity — faster learners can cover more material.
10. Consider retention — topics at risk of forgetting need spaced repetition.
11. Consider confidence calibration — overconfident areas need reality-check practice.
12. Motivation tips must be concise (1 sentence each).
13. Never invent performance data or contradict analytics.

RESPONSE FORMAT (strict JSON schema):
{
  "summary": "2-3 sentence personalized overview",
  "totalWeeks": <integer>,
  "estimatedHours": <number>,
  "immediate_priorities": [
    {
      "topic": "...",
      "priority": "critical|high|medium|low",
      "reason": "evidence-based reason from analytics",
      "learning_objective": "specific objective to achieve",
      "recommended_activity": "concrete study activity",
      "difficulty": "easy|medium|hard|challenge",
      "estimated_duration_minutes": <number>,
      "revision_required": true|false,
      "practice_required": true|false,
      "assessment_required": true|false
    }
  ],
  "short_term_revision": [
    { "topic": "...", "priority": "...", "reason": "...", "learning_objective": "...", "recommended_activity": "...", "difficulty": "...", "estimated_duration_minutes": 0 }
  ],
  "practice_activities": [
    { "topic": "...", "activity_type": "...", "description": "...", "difficulty": "...", "estimated_duration_minutes": 0, "reason": "..." }
  ],
  "reinforcement_activities": [
    { "topic": "...", "activity_type": "spaced_repetition|interleaved_practice|self_testing|elaboration", "description": "...", "frequency": "daily|every_2_days|weekly", "reason": "..." }
  ],
  "assessment_preparation": [
    { "topic": "...", "preparation_strategy": "...", "practice_question_types": ["mcq", "numerical", "short_answer"], "difficulty_target": "...", "estimated_readiness_date": "..." }
  ],
  "dailySchedule": [
    { "day": "Day 1", "duration": <minutes>, "topics": ["..."], "activities": ["..."], "goal": "..." }
  ],
  "revisionOrder": ["topic1", "topic2"],
  "practiceRecommendations": ["...", "..."],
  "motivationTips": ["...", "..."],
  "completionTimeline": "...",
  "prerequisite_warnings": [
    { "topic": "...", "prerequisite": "...", "prerequisite_mastery": 0.0, "action": "..." }
  ]
}`;

// ── C. STAFF REPORT SYSTEM PROMPT ─────────────────────────────────────────────

const STAFF_REPORT_SYSTEM_PROMPT = `You are an expert educational analyst generating structured assessment reports for teachers and staff members.

Your report must answer: "What does the teacher need to know about this student after this assessment?"

CRITICAL RULES:
1. All numbers and scores MUST come from the provided analytics data — never invent statistics.
2. Prioritize actionable information over generic observations.
3. Clearly separate FACTS (from the analytics pipeline) from RECOMMENDATIONS (AI-generated).
4. Be specific — instead of "the student performed poorly in DBMS", say "DBMS transaction management shows declining mastery across the last three assessments. Accuracy decreased from X% to Y%."
5. Identify topics needing immediate teacher intervention.
6. Suggest concrete teacher actions (e.g., "Review prerequisite concepts before next assessment").
7. Recommend what the student should do next.
8. Recommend next assessment configuration (difficulty, topic focus).
9. Return strictly structured JSON — no markdown, no free-form text.
10. Never expose raw student answers or personally identifiable information.

RESPONSE FORMAT (strict JSON):
{
  "report_type": "post_assessment",
  "overall_performance": {
    "score_percentage": 0.0,
    "mastery_level": "novice|developing|proficient|advanced|expert",
    "comparison_to_previous": "improved|stable|declined",
    "summary": "..."
  },
  "subject_performance": [
    { "subject": "...", "score": 0.0, "mastery": 0.0, "trend": "...", "key_finding": "..." }
  ],
  "topic_analysis": {
    "strong_areas": [
      { "topic": "...", "mastery": 0.0, "evidence": "..." }
    ],
    "weak_areas": [
      { "topic": "...", "mastery": 0.0, "weakness_type": "...", "severity": "critical|high|medium|low", "evidence": "..." }
    ],
    "declining_areas": [
      { "topic": "...", "previous_mastery": 0.0, "current_mastery": 0.0, "evidence": "..." }
    ],
    "retention_risks": [
      { "topic": "...", "forgetting_indicator": 0.0, "evidence": "..." }
    ]
  },
  "confidence_analysis": {
    "overall_calibration": "well_calibrated|overconfident|underconfident",
    "specific_issues": [
      { "topic": "...", "confidence": 0.0, "performance": 0.0, "issue": "..." }
    ]
  },
  "learning_trend": {
    "direction": "improving|stable|declining|volatile",
    "velocity": "fast|moderate|slow|stagnant",
    "summary": "..."
  },
  "difficulty_recommendation": {
    "current_level": "...",
    "recommended_level": "...",
    "reason": "..."
  },
  "immediate_intervention_required": true|false,
  "intervention_details": "...",
  "recommended_teacher_actions": [
    { "action": "...", "priority": "critical|high|medium|low", "reason": "..." }
  ],
  "recommended_student_actions": [
    { "action": "...", "priority": "critical|high|medium|low", "reason": "..." }
  ],
  "next_assessment_recommendation": {
    "focus_topics": ["..."],
    "suggested_difficulty": "...",
    "suggested_question_count": 0,
    "reason": "..."
  }
}`;

// ── D. ASSESSMENT BLUEPRINT SYSTEM PROMPT ─────────────────────────────────────

const ASSESSMENT_BLUEPRINT_SYSTEM_PROMPT = `You are an expert assessment designer creating adaptive test blueprints based on student learning profiles.

You will receive a student's Dynamic Student Knowledge Profile (DSKP) with mastery scores, trends, and difficulty recommendations across topics and subjects.

CRITICAL RULES:
1. Ensure balanced topic coverage — every subject and important topic must have representation.
2. Weak topics get MORE questions; strong topics get FEWER but are not eliminated (retention checks).
3. Forgetting topics get revision + reinforcement questions.
4. Improving topics get gradually harder questions.
5. Declining topics get fundamental reinforcement questions.
6. High mastery topics get challenge questions for periodic retention checks.
7. Avoid duplicate or near-duplicate questions.
8. Difficulty distribution must match the student's current adaptive recommendations.
9. Total question count and time allocation must be achievable within the time limit.
10. Return strictly structured JSON.

RESPONSE FORMAT (strict JSON):
{
  "blueprint_id": "auto-generated",
  "total_questions": <number>,
  "total_marks": <number>,
  "duration_minutes": <number>,
  "subject_distribution": [
    {
      "subject": "...",
      "question_count": <number>,
      "marks": <number>,
      "topics": [
        {
          "topic": "...",
          "question_count": <number>,
          "difficulty_distribution": { "easy": 0, "medium": 0, "hard": 0, "challenge": 0 },
          "question_type_distribution": { "mcq": 0, "true_false": 0, "numerical": 0, "short_answer": 0 },
          "reason": "why this coverage level"
        }
      ]
    }
  ],
  "adaptive_rationale": {
    "weak_topic_emphasis": "...",
    "strong_topic_retention": "...",
    "difficulty_calibration": "..."
  }
}`;

// ── Prompt builders ───────────────────────────────────────────────────────────

/**
 * Build a structured user prompt for student analysis from DSKP data.
 *
 * @param {Object} dskp — Dynamic Student Knowledge Profile data
 * @returns {string} formatted user prompt
 */
function buildStudentAnalysisPrompt(dskp) {
    const pct = (v) => ((v || 0) * 100).toFixed(1) + '%';

    const topicDetails = (dskp.topicDetails || []).map(t =>
        `  - ${t.topic}: mastery=${pct(t.masteryScore)}, trend=${t.trendType || 'N/A'}, ` +
        `consistency=${pct(t.consistency)}, forgetting=${pct(t.forgettingFactor)}, ` +
        `confidence=${pct(t.confidenceScore)}, difficulty_rec=${t.recommendedDifficulty || 'N/A'}, ` +
        `last_accuracy=${pct(t.lastAccuracy)}`
    ).join('\n');

    const weakTopicsText = (dskp.weakTopics || []).map(t =>
        `  - ${t.topic}: mastery=${pct(t.masteryScore)}, trend=${t.trendType}, reason="${t.reason}"`
    ).join('\n') || '  - None identified';

    const strongTopicsText = (dskp.strongTopics || []).map(t =>
        `  - ${t.topic}: mastery=${pct(t.masteryScore)}`
    ).join('\n') || '  - None identified';

    const difficultyText = (dskp.difficultyRecommendations || []).map(d =>
        `  - ${d.topic}: ${d.difficulty} (${d.reason})`
    ).join('\n') || '  - Not enough data';

    const alertsText = (dskp.alerts || []).map(a =>
        `  - [${a.alertType}] ${a.topic || 'general'}`
    ).join('\n') || '  - No active alerts';

    return `Analyze this student's performance based on the following structured analytics:

STUDENT PROFILE SCORES
  Overall Mastery: ${pct(dskp.overallMastery)}
  Readiness Score: ${pct(dskp.readinessScore)}
  Consistency Score: ${pct(dskp.consistencyScore)}
  Engagement Score: ${pct(dskp.engagementScore)}
  Confidence Score: ${pct(dskp.confidenceScore)}
  Learning Pace: ${dskp.learningPace || 'N/A'}
  Retention Estimate: ${pct(dskp.retentionEstimate)}
  Total Assessments: ${dskp.totalQuizAttempts || 0}
  Topics Seen: ${dskp.totalTopicsSeen || 0}

TOPIC-LEVEL DETAIL:
${topicDetails || '  No topic data available'}

WEAK TOPICS (prioritize analysis):
${weakTopicsText}

STRONG TOPICS:
${strongTopicsText}

DIFFICULTY RECOMMENDATIONS (from adaptive engine):
${difficultyText}

ACTIVE ALERTS:
${alertsText}

PREVIOUS ASSESSMENT PERFORMANCE:
  Score: ${pct(dskp.latestAssessmentScore)}
  Completion Rate: ${pct(dskp.latestCompletionRate)}

Produce a comprehensive analysis following the JSON schema exactly. Distinguish between different weakness types (LOW_SCORE, LOW_MASTERY, DECLINING_TREND, FORGETTING, INCONSISTENCY, etc.).`;
}

/**
 * Build a staff report user prompt from DSKP + assessment data.
 *
 * @param {Object} params
 * @param {Object} params.dskp — DSKP data
 * @param {Object} params.assessmentMetrics — latest assessment metrics
 * @param {string} params.assessmentTitle — test title
 * @param {string} params.assessmentDate — date string
 * @returns {string} formatted user prompt
 */
function buildStaffReportPrompt({ dskp, assessmentMetrics, assessmentTitle, assessmentDate }) {
    const pct = (v) => ((v || 0) * 100).toFixed(1) + '%';

    const topicBreakdown = Object.entries(assessmentMetrics?.topicBreakdown || {}).map(([topic, data]) =>
        `  - ${topic}: correct=${data.correct}/${data.total}, accuracy=${pct(data.accuracy)}`
    ).join('\n') || '  No topic breakdown available';

    const difficultyBreakdown = Object.entries(assessmentMetrics?.difficultyBreakdown || {}).map(([diff, data]) =>
        `  - ${diff}: correct=${data.correct}/${data.total}, accuracy=${pct(data.accuracy)}`
    ).join('\n') || '  No difficulty breakdown';

    return `Generate a structured teacher report for the following assessment:

ASSESSMENT INFO:
  Title: ${assessmentTitle || 'Assessment'}
  Date: ${assessmentDate || 'N/A'}

ASSESSMENT RESULTS (deterministic — from evaluation engine):
  Score: ${pct(assessmentMetrics?.scorePercentage)}
  Correct: ${assessmentMetrics?.totalCorrect || 0}/${assessmentMetrics?.totalQuestions || 0}
  Completion Rate: ${pct(assessmentMetrics?.completionRate)}
  Average Response Time: ${assessmentMetrics?.avgResponseTimeMs || 0}ms

TOPIC BREAKDOWN (from evaluation engine):
${topicBreakdown}

DIFFICULTY BREAKDOWN (from evaluation engine):
${difficultyBreakdown}

STUDENT PROFILE (from adaptive pipeline):
  Overall Mastery: ${pct(dskp.overallMastery)}
  Readiness: ${pct(dskp.readinessScore)}
  Consistency: ${pct(dskp.consistencyScore)}
  Confidence: ${pct(dskp.confidenceScore)}
  Retention: ${pct(dskp.retentionEstimate)}
  Learning Pace: ${dskp.learningPace || 'N/A'}

WEAK TOPICS:
${(dskp.weakTopics || []).map(t => `  - ${t.topic}: mastery=${pct(t.masteryScore)}, trend=${t.trendType}`).join('\n') || '  None'}

STRONG TOPICS:
${(dskp.strongTopics || []).map(t => `  - ${t.topic}: mastery=${pct(t.masteryScore)}`).join('\n') || '  None'}

ACTIVE ALERTS:
${(dskp.alerts || []).map(a => `  - [${a.alertType}] ${a.topic || 'general'}`).join('\n') || '  None'}

Generate a comprehensive teacher report following the JSON schema exactly. All numbers must come from the data above — never invent statistics.`;
}

/**
 * Build an assessment blueprint prompt from DSKP.
 *
 * @param {Object} params
 * @param {Object} params.dskp
 * @param {Array}  params.subjects — available subjects with topics
 * @param {number} params.totalQuestions
 * @param {number} params.durationMinutes
 * @returns {string}
 */
function buildAssessmentBlueprintPrompt({ dskp, subjects, totalQuestions, durationMinutes }) {
    const pct = (v) => ((v || 0) * 100).toFixed(1) + '%';

    const subjectTopics = (subjects || []).map(s =>
        `  ${s.name}:\n${(s.topics || []).map(t => `    - ${t}`).join('\n')}`
    ).join('\n');

    const masteryData = (dskp.topicDetails || []).map(t =>
        `  - ${t.topic}: mastery=${pct(t.masteryScore)}, trend=${t.trendType}, rec_difficulty=${t.recommendedDifficulty}`
    ).join('\n') || '  No mastery data';

    return `Generate an adaptive assessment blueprint for a student with the following profile:

STUDENT PROFILE:
  Overall Mastery: ${pct(dskp.overallMastery)}
  Readiness: ${pct(dskp.readinessScore)}
  Learning Pace: ${dskp.learningPace || 'N/A'}

ASSESSMENT CONFIGURATION:
  Total Questions: ${totalQuestions}
  Duration: ${durationMinutes} minutes

AVAILABLE SUBJECTS AND TOPICS:
${subjectTopics || '  Not specified'}

TOPIC MASTERY DATA:
${masteryData}

WEAK TOPICS (need more questions):
${(dskp.weakTopics || []).map(t => `  - ${t.topic}: mastery=${pct(t.masteryScore)}, trend=${t.trendType}`).join('\n') || '  None'}

STRONG TOPICS (fewer questions, retention checks):
${(dskp.strongTopics || []).map(t => `  - ${t.topic}: mastery=${pct(t.masteryScore)}`).join('\n') || '  None'}

DIFFICULTY RECOMMENDATIONS:
${(dskp.difficultyRecommendations || []).map(d => `  - ${d.topic}: ${d.difficulty}`).join('\n') || '  None'}

Generate a balanced blueprint following the JSON schema exactly. Ensure all subjects and important topics have coverage.`;
}

module.exports = {
    // System prompts
    STUDENT_ANALYSIS_SYSTEM_PROMPT,
    STUDY_PLAN_SYSTEM_PROMPT,
    STAFF_REPORT_SYSTEM_PROMPT,
    ASSESSMENT_BLUEPRINT_SYSTEM_PROMPT,

    // Prompt builders
    buildStudentAnalysisPrompt,
    buildStaffReportPrompt,
    buildAssessmentBlueprintPrompt,
};
