const mongoose = require('mongoose');
const crypto   = require('crypto');

/**
 * AICache — persistent MongoDB cache for AI-generated responses.
 *
 * Cache lifecycle:
 *   isValid = true  → cache hit, return cachedResponse
 *   isValid = false → cache miss, call Groq and refresh
 *
 * Invalidation is triggered when a test attempt is submitted:
 *   all entries with relatedTestId matching the completed test are set isValid = false.
 *
 * Supports two lookup strategies:
 *   1. cacheKey (string) — used by groqService.js (preferred)
 *   2. userId + endpointName + inputHash — used by ai-cache-service.js (legacy)
 */
const aiCacheSchema = new mongoose.Schema({
    // Primary cache key (generated by caller — typically a hash of inputs)
    cacheKey: {
        type: String,
        index: true,
        default: '',
    },
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        required: true,
        index: true,
    },
    userRole: {
        type: String,
        enum: ['teacher', 'student', 'admin', 'system'],
        default: 'system',
    },
    endpointName: {
        type: String,
        required: true,
    },
    // SHA-256 hex of the serialised request input (legacy lookup key)
    inputHash: {
        type: String,
        default: '',
    },
    cachedResponse: {
        type: mongoose.Schema.Types.Mixed,
        required: true,
    },
    relatedTestId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'test',
        default: null,
        index: true,
    },
    isValid: {
        type: Boolean,
        default: true,
        index: true,
    },
    createdAt: {
        type: Date,
        default: Date.now,
        // TTL index: auto-delete documents after 30 days regardless of isValid
        expires: 60 * 60 * 24 * 30,
    },
});

// Primary lookup index (groqService)
aiCacheSchema.index({ cacheKey: 1, isValid: 1 });
// Legacy lookup index (ai-cache-service)
aiCacheSchema.index({ userId: 1, endpointName: 1, inputHash: 1 });
// Invalidation index
aiCacheSchema.index({ relatedTestId: 1, isValid: 1 });

/**
 * Static helper: generate a SHA-256 hash of any input object.
 * Used to produce a stable, compact cache key from request parameters.
 */
aiCacheSchema.statics.hashInput = function (inputObj) {
    const str = JSON.stringify(inputObj, Object.keys(inputObj).sort());
    return crypto.createHash('sha256').update(str).digest('hex');
};

module.exports = mongoose.model('aiCache', aiCacheSchema);
