const mongoose = require("mongoose");

// ── Embedded: Exam Result ────────────────────────────────────────────────────
const examResultSchema = new mongoose.Schema({
    subjectId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "subject",
        required: true
    },
    topic:     { type: String },
    marks:     { type: Number, default: 0 },
    maxMarks:  { type: Number, default: 100 },
    examDate:  { type: Date, default: Date.now },
}, { _id: false });

// ── Embedded: Attendance ─────────────────────────────────────────────────────
const attendanceSchema = new mongoose.Schema({
    date: { type: Date, required: true },
    subjectId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "subject",
        required: true
    },
    status:      { type: String, enum: ["Present", "Absent"], required: true },
    sessionType: { type: String, enum: ["lecture", "lab", "exam"], default: "lecture" },
}, { _id: false });

// ── Student ──────────────────────────────────────────────────────────────────
const studentSchema = new mongoose.Schema({
    name:     { type: String, required: true },
    rollNum:  { type: Number, required: true },
    password: { type: String, required: true }, // bcrypt hashed
    role:     { type: String, default: "Student" },

    classId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "sclass",
        required: true
    },
    // kept as alias so existing controllers still work
    sclassName: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "sclass"
    },
    parentId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "parent"
    },
    schoolId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "admin",
        required: true
    },
    // kept as alias so existing controllers still work
    school: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "admin"
    },

    // ── Status & parent info ───────────────────────────────────────────────
    status: {
        type: String,
        enum: ['active', 'inactive', 'suspended'],
        default: 'active',
    },
    parentName:  { type: String },
    parentPhone: { type: String },

    // ── AI / Analytics fields ──────────────────────────────────────────────
    behaviorScore: { type: Number, default: 50, min: 0, max: 100 },
    focusIndex:    { type: Number, default: 5,  min: 0, max: 10  },

    // { "Algebra": 85, "Trigonometry": 72, ... }
    conceptMastery: {
        type: Map,
        of: Number,
        default: {}
    },

    // warning signals generated by AI
    learningFlags: [{
        flag: {
            type: String,
            enum: ["at_risk", "struggling", "improving", "excelling"]
        },
        subject:    { type: mongoose.Schema.Types.ObjectId, ref: "subject" },
        detectedAt: { type: Date, default: Date.now },
        isActive:   { type: Boolean, default: true }
    }],

    // ── Embedded arrays ────────────────────────────────────────────────────
    examResult: [examResultSchema],
    attendance: [attendanceSchema],

}, { timestamps: true });

// ── Pre-save: keep aliases in sync ───────────────────────────────────────────
studentSchema.pre("save", function (next) {
    if (this.classId  && !this.sclassName) this.sclassName = this.classId;
    if (this.sclassName && !this.classId)  this.classId    = this.sclassName;
    if (this.schoolId && !this.school)     this.school     = this.schoolId;
    if (this.school   && !this.schoolId)   this.schoolId   = this.school;
    next();
});

studentSchema.index({ schoolId: 1 });
studentSchema.index({ classId: 1 });
studentSchema.index({ rollNum: 1, classId: 1 });
// Login query: roll number + class (unique per class)
studentSchema.index({ rollNum: 1, classId: 1 }, { unique: true });
// Teacher class view: all students in a class
studentSchema.index({ classId: 1, name: 1 });
// Exam result subject lookup (multikey on embedded array)
studentSchema.index({ "examResult.subjectId": 1 });
// Attendance subject lookup (multikey on embedded array)
studentSchema.index({ "attendance.subjectId": 1 });

module.exports = mongoose.model("student", studentSchema);
